name: DobbyBot
author: opensourcetech@simplybusiness.co.uk
description:
  A Github action which provides chat-ops functionality through PR comments. 
branding:
  icon: code
  color: red
runs:
  using: 'docker'
  image: 'Dockerfile'
